instruction_bin: "cat/instr.bin"
data_bin: "cat/data.bin"

debug: false
log_file: "cat/logs/cpu.log"

tick_limit: 1000
schedule:
  - tick: 50
    input:
      interrupt: 1
      value: "G"
  - tick: 400
    input:
      interrupt: 1
      value: "o"
  - tick: 700
    input:
      interrupt: 1
      value: "i"

max_interruptions: 2
