instruction_bin: "hello_user/instr.bin"
data_bin: "hello_user/data.bin"
debug: false
log_file: "cpu.log"

tick_limit: 10000
schedule:
  - tick: 50
    input:
      interrupt: 1
      value: "G"
  - tick: 400
    input:
      interrupt: 1
      value: "o"
  - tick: 700
    input:
      interrupt: 1
      value: "i"

max_interruptions: 2
