instruction_bin: "bin/instr.bin"
data_bin: "bin/data.bin"

tick_limit: 400
# schedule:
#   - tick: 100
#     input:
#       interrupt: 1
#       value: "A"
#   - tick: 200
#     input:
#       interrupt: 1
#       value: "C"
#   - tick: 400
#     input:
#       interrupt: 0
#       value: "B"
#   - tick: 550
#     input:
#       interrupt: 0
#       value: "C"

max_interruptions: 2
