instruction_bin: "bin/instr.bin"
data_bin: "bin/data.bin"

tick_limit: 1000
schedule:
  - tick: 50
    input:
      interrupt: 1
      value: "G"
  - tick: 200
    input:
      interrupt: 1
      value: "o"
  - tick: 400
    input:
      interrupt: 1
      value: "i"
#   - tick: 550
#     input:
#       interrupt: 0
#       value: "C"

max_interruptions: 2
