instruction_bin: "sort/instr.bin"
data_bin: "sort/data.bin"
debug: false
log_file: "cpu.log"

tick_limit: 10000
schedule:
  - tick: 80
    input:
      interrupt: 0
      value: 4
  - tick: 150
    input:
      interrupt: 0
      value: 2
  - tick: 400
    input:
      interrupt: 0
      value: 1
  - tick: 700
    input:
      interrupt: 0
      value: 3
  - tick: 1000
    input:
      interrupt: 0
      value: 0

max_interruptions: 2
