# name: deploy
#
# on:
#   push:
#     branches: [main]
#
# env:
#   IMAGE: ghcr.io/${{ github.repository_owner }}/csa-lab4-web
#
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#
#       - uses: docker/setup-buildx-action@v3
#
#       - uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#
#       - uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ env.IMAGE }}:latest
#             ${{ env.IMAGE }}:${{ github.sha }}
#
#   deploy:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#       - name: Remote rollout
#         uses: appleboy/ssh-action@v0.1.8
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             docker pull $IMAGE:latest
#             docker stop csa-lab4-web || true
#             docker rm   csa-lab4-web || true
#             docker run -d --name csa-lab4-web --restart unless-stopped -p 8080:8080 $IMAGE:latest
